import Link from "next/link";
import Script from "next/script";
import type { Metadata } from "next";
import TrainingApp from "@/components/TrainingApp";
export const metadata: Metadata = {title:"온라인 발성훈련 | VoiSpeech",robots:{index:false,follow:false}};
export default function Training(){return <TrainingApp><div className="academy" id="academy">
 <header className="academy-header"><Link className="academy-brand" href="/">VoiSpeech <span>ONLINE STUDIO</span></Link></header>
 <div className="academy-shell"><aside className="academy-sidebar"><p className="eyebrow">MY VOICE PRACTICE</p><nav aria-label="온라인 훈련 메뉴"><button data-tab="library" aria-pressed="true">훈련 <span>↗</span></button><button data-tab="community" aria-pressed="false">커뮤니티</button><button data-tab="progress" aria-pressed="false">연습 기록</button><button data-tab="membership" aria-pressed="false">마이</button></nav><div className="sidebar-note"><span>수업과 수업 사이에도</span><p>나의 속도로,<br/>다시 연습하는 시간.</p></div><Link href="/#booking">1:1 레슨 예약 ↗</Link><button data-action="reset" className="academy-reset">체험 처음부터</button></aside>
 <main id="main-content" className="academy-main">
 <section data-panel="library"><div className="academy-heading"><div><p className="eyebrow">YOUR VOICE, YOUR PACE</p><h1>오늘도, 내 목소리와<br/>조금 더 가까이.</h1><p>수업에서 찾은 감각을 떠올리며<br className="mobile-break"/> 나에게 필요한 연습을 골라보세요.</p></div><div className="practice-count"><strong id="completion-count">0 / 4</strong><span>완료한 영상 · 체험 기록</span></div></div>
 <div className="feature-lesson"><div><span className="academy-chip">START HERE · 무료 미리보기</span><h2>연습을 시작하기 전에</h2><p>온라인 훈련관을 먼저 둘러보세요.</p><button data-lesson="1" className="academy-light">미리보기 재생 <span>▷</span></button></div><div className="feature-word" aria-hidden="true">VOICE<br/><span>PRACTICE</span></div></div>
 <div className="learning-path"><p className="eyebrow">나의 학습 경로</p><div>{["기초 이해","내 발성 관찰","루틴 연습","노래 적용"].map((t,i)=><button key={t} data-path={i}><span>0{i+1}</span>{t}</button>)}</div><p id="path-description">기초 이해부터 시작해, 필요한 연습을 골라 노래에 적용해 보세요.</p></div><label className="course-search">코스 검색<input id="course-search" type="search" placeholder="제목 · 소제목 · 카테고리 · 내용 검색"/></label><div className="library-top"><h2>영상 라이브러리</h2><div className="academy-filters" aria-label="영상 분류"><button data-filter="전체" aria-pressed="true">전체</button></div></div>
 <div className="lesson-grid"></div>
 <div className="academy-subscribe"><div><span className="eyebrow">VOISPEECH MEMBERSHIP</span><h2>나의 연습을 이어가는 공간.</h2><p>구독하면 모든 예시 강의를 열어볼 수 있습니다.</p></div><div><p><strong>월 29,000원</strong> <span>예시 가격</span></p><button className="btn-primary" data-action="subscribe">구독 체험하기 ↗</button></div></div>
 </section>
 <section data-panel="progress" hidden><p className="eyebrow">MY PRACTICE</p><h1>나의 학습 기록</h1><p className="academy-description">완료 표시한 영상을 다시 찾아보세요. 로그인하면 체크인이 계정에 저장됩니다.</p><form id="practice-form" className="practice-form"><h2>오늘의 체크인</h2><p>로그인 시 계정에 저장됩니다. 비로그인은 이 화면에만 남습니다.</p><label>종류<select name="kind"><option>발성 연습</option><option>곡 연습</option><option>강의 시청</option></select></label><label>연습 시간 (분)<input name="minutes" type="number" min="1" max="600" required defaultValue="10"/></label><label>오늘의 곡 / 메모<input name="note" maxLength={120} placeholder="연습한 곡이나 느낀 점"/></label><button className="btn-primary" type="submit">체험 기록 추가</button></form><div className="record-summary" id="record-summary">기록 0회 · 총 0분</div><div id="checkin-list"/><div id="progress-list" className="progress-list"><p>아직 완료한 영상이 없어요. 무료 미리보기부터 시작해 보세요.</p></div><button className="btn-primary" data-tab="library">영상 보러 가기</button></section>
 <section data-panel="community" hidden><p className="eyebrow">VOISPEECH COMMUNITY</p><h1>함께 연습하는 공간</h1><p className="academy-description">로그인하면 채널별 글이 저장됩니다. 비로그인은 작성할 수 없습니다.</p><div className="community-channels">{["공지","질문","연습 나눔","작은 변화"].map((t,i)=><button key={t} data-channel={t} aria-pressed={i===0}>{t}</button>)}</div><div id="community-feed"><article className="community-post"><span>운영 안내 · 예시</span><h2>나의 연습을 짧게 남겨보세요.</h2><p>잘 된 점 한 가지, 다음에 확인할 점 한 가지부터 시작합니다.</p></article></div><form id="community-form" className="practice-form"><label>체험 글 작성<textarea name="post" required maxLength={500} placeholder="로그인 후 작성할 수 있습니다."/></label><button className="btn-primary">로그인 후 작성</button></form></section><section data-panel="membership" hidden><p className="eyebrow">MEMBERSHIP</p><h1>나의 훈련 공간</h1><h2 className="saved-heading">저장한 코스</h2><div id="favorites-list" className="progress-list">저장한 코스가 없습니다.</div><h2>구독 관리</h2><p className="academy-description">구독 시작과 해지 흐름을 확인하는 예시 화면입니다.</p><div className="membership-card"><span className="academy-chip" id="subscription-state">구독 전</span><h2>VoiSpeech 온라인 발성훈련</h2><p className="membership-price">월 29,000원 <small>예시 가격 · 실제 청구 없음</small></p><p id="subscription-detail">구독 체험을 시작하면 전용 영상이 열립니다.</p><div className="membership-actions"><button className="btn-primary" data-action="subscribe">구독 체험하기</button><button className="btn-outline" data-action="cancel" hidden>자동 갱신 해지 체험</button><button className="btn-outline" data-action="expire" hidden>이용기간 만료 체험</button></div></div></section>
 <p className="academy-footnote">업로드된 강의가 있으면 해당 영상이 재생됩니다. 없으면 재생 확인용 샘플이 사용됩니다.</p>
 <p id="academy-status" role="status" className="academy-status"></p>
 </main></div>
 <dialog id="checkout-dialog" className="academy-dialog" aria-labelledby="checkout-title"><div className="dialog-heading"><span className="eyebrow">MEMBERSHIP PREVIEW</span><button data-close="checkout-dialog" aria-label="닫기">✕</button></div><h2 id="checkout-title">구독을 시작해 볼까요?</h2><p>실제 결제 없이 구독자 화면을 체험합니다.</p><dl className="checkout-details"><div><dt>상품</dt><dd>온라인 발성훈련 멤버십</dd></div><div><dt>결제 주기 예시</dt><dd>매월</dd></div><div><dt>월 이용료 예시</dt><dd>29,000원</dd></div><div><dt>이번 체험 청구 금액</dt><dd>0원 · 결제 없음</dd></div></dl><p className="checkout-notice">카드번호나 개인정보를 입력하지 않습니다. 구독 상태는 이 화면 안에서만 바뀝니다.</p><button data-action="pay" className="btn-primary">결제 없이 구독자 화면 체험</button></dialog>
 <dialog id="player-dialog" className="academy-dialog player-dialog" aria-labelledby="player-title"><div className="dialog-heading"><span className="eyebrow">VIDEO PREVIEW</span><button data-close="player-dialog" aria-label="영상 닫기">✕</button></div><h2 id="player-title">연습을 시작하기 전에</h2><p id="player-description" className="player-description" hidden></p><div id="module-list" className="module-list"/><video id="lesson-video" controls playsInline preload="none" src="/training-sample.mp4" aria-label="실제 강의가 아닌 재생 확인용 10초 무음 영상"/><div id="player-body" className="player-body" hidden></div><p id="player-hint">10초 재생 테스트 · 무음 · 실제 강의가 아닙니다.</p><button data-action="complete" className="btn-primary">이 단계 완료 · 다음 단계</button></dialog>
 <dialog id="cancel-dialog" className="academy-dialog" aria-labelledby="cancel-title"><div className="dialog-heading"><span className="eyebrow">SUBSCRIPTION</span><button data-close="cancel-dialog" aria-label="닫기">✕</button></div><h2 id="cancel-title">자동 갱신을 해지할까요?</h2><p>이 예시에서는 자동 갱신을 해지해도 이용기간이 끝나기 전까지 전용 영상이 열려 있습니다.</p><button className="btn-primary" data-action="confirm-cancel">해지 체험하기</button></dialog>
 <nav className="academy-bottom" aria-label="하단 메뉴">{[["library","훈련"],["community","커뮤니티"],["progress","기록"],["membership","마이"]].map(([id,t])=><button key={id} data-tab={id} aria-pressed={id==="library"}>{t}</button>)}</nav><Script src="/training-demo.js" strategy="afterInteractive"/>
 </div></TrainingApp>}
